"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-04-20 23:21:25.401899

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Integer(), server_default='0', nullable=False),
    sa.Column('base_params_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index('ix_presets_material_id', ['material_id'], unique=False)

    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('locked', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('created','tested','deleted')", name='tests_status_chk'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index('ix_tests_material_id', ['material_id'], unique=False)
        batch_op.create_index('ix_tests_status', ['status'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.Text(), nullable=False),
    sa.Column('excluded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('swatches_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('ix_results_test_id', ['test_id'], unique=False)

    op.create_table('palette_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('x_value', sa.Float(), nullable=True),
    sa.Column('y_value', sa.Float(), nullable=True),
    sa.Column('hex', sa.Text(), nullable=False),
    sa.Column('lab_l', sa.Float(), nullable=False),
    sa.Column('lab_a', sa.Float(), nullable=False),
    sa.Column('lab_b', sa.Float(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_result_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('averaged','single_result')", name='palette_entries_source_chk'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['source_result_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('palette_entries', schema=None) as batch_op:
        batch_op.create_index('ix_palette_entries_material_id', ['material_id'], unique=False)
        batch_op.create_index('ix_palette_entries_test_id', ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palette_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_palette_entries_test_id')
        batch_op.drop_index('ix_palette_entries_material_id')

    op.drop_table('palette_entries')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_test_id')

    op.drop_table('results')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index('ix_tests_status')
        batch_op.drop_index('ix_tests_material_id')

    op.drop_table('tests')
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index('ix_presets_material_id')

    op.drop_table('presets')
    op.drop_table('materials')
    # ### end Alembic commands ###
