"""Per-material/machine text+registration param defaults

Two tables that drive QR + ArUco fiducials, axis-tick + label glyphs,
and the summary-text strip burned above the cell grid:

* ``text_reg_defaults_machine``: one row per (owner_id, machine_id).
  Fallback when a material doesn't have its own override.
* ``text_reg_defaults_material``: one row per (owner_id, machine_id,
  material_id). Wins over the machine fallback when present.

Resolution at burn time:
    test override → material default → machine default → built-in constants

Param columns mirror ``xcs_gen.model.ProcessingParams``. First-class
columns (not a JSON blob) so future "list every material I've
calibrated for the F2" lookups stay in SQL. See models.py for the
SQLAlchemy table source-of-truth.

Body autogenerated via ``alembic revision --autogenerate`` against
the new tables in models.py, with unrelated pre-existing column-type
drift (between older migrations and current model declarations)
pruned per CLAUDE.md guidance — that drift is its own cleanup pass,
not this PR's scope.

Revision ID: 0018
Revises: 0017
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


_PARAM_COLS = (
    sa.Column("speed", sa.Integer(), nullable=False),
    sa.Column("power", sa.Float(), nullable=False),
    sa.Column("density", sa.Integer(), nullable=False),
    sa.Column("repeat", sa.Integer(), nullable=False),
    sa.Column("pulse_width", sa.Integer(), nullable=False),
    sa.Column("mopa_frequency", sa.Integer(), nullable=False),
    sa.Column(
        "processing_light_source", sa.String(length=16),
        server_default="red", nullable=False,
    ),
)


def upgrade() -> None:
    op.create_table(
        "text_reg_defaults_machine",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.String(length=32), nullable=False),
        *_PARAM_COLS,
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "machine_id",
            name="uq_text_reg_defaults_machine",
        ),
    )
    with op.batch_alter_table("text_reg_defaults_machine", schema=None) as batch_op:
        batch_op.create_index(
            "ix_text_reg_defaults_machine_owner",
            ["owner_id"], unique=False,
        )

    op.create_table(
        "text_reg_defaults_material",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.String(length=32), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        *_PARAM_COLS,
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "machine_id", "material_id",
            name="uq_text_reg_defaults_material",
        ),
    )
    with op.batch_alter_table("text_reg_defaults_material", schema=None) as batch_op:
        batch_op.create_index(
            "ix_text_reg_defaults_material_lookup",
            ["owner_id", "machine_id", "material_id"], unique=False,
        )
        batch_op.create_index(
            "ix_text_reg_defaults_material_owner",
            ["owner_id"], unique=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("text_reg_defaults_material", schema=None) as batch_op:
        batch_op.drop_index("ix_text_reg_defaults_material_owner")
        batch_op.drop_index("ix_text_reg_defaults_material_lookup")
    op.drop_table("text_reg_defaults_material")
    with op.batch_alter_table("text_reg_defaults_machine", schema=None) as batch_op:
        batch_op.drop_index("ix_text_reg_defaults_machine_owner")
    op.drop_table("text_reg_defaults_machine")
